### Signup
POST http://localhost:3010/signup
Content-Type: application/json

{
  "name": "Test",
  "mail": "test1@mail.com",
  "authenticationString": "123",
  "age": 20,
  "country": "US"
}


### Login
POST http://localhost:3010/login
Content-Type: application/json

{
  "mail": "test1@mail.com",
  "authenticationString": "123"
}


### Logout
POST http://localhost:3010/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0MmMzMjcxYWM2ZDZlZjgzYTAwMDNmZSIsIm5hbWUiOiJUZXN0IiwibWFpbCI6InRlc3QxQG1haWwuY29tIiwiYXV0aGVudGljYXRpb25TdHJpbmciOiIkMmIkMTIkTXA5TWhEL1pJMHE3S1RERDEueXR4ZUNhV2JlODRDVWh5U2FtcHN1Q0pkUlQwT0FUajVOdHUiLCJhZ2UiOjIwLCJjb3VudHJ5IjoiVVMiLCJfX3YiOjB9LCJpYXQiOjE2ODA2MTg3MTgsImV4cCI6MTY4MDYyMjMxOH0.DNLxlMJsoe3XAVdsgK5w47Kz5EZ1bKTOlz6AFqzRGWM

