### Signup
POST {{address}}/signup
Content-Type: application/json

{
  "name": "Test",
  "mail": "test1@mail.com",
  "authenticationString": "123",
  "age": 20,
  "country": "US"
}

### Login
POST {{address}}/login
Content-Type: application/json

{
  "mail": "test1@mail.com",
  "authenticationString": "123"
}


### Profile
GET {{address}}/profile
Content-Type: application/json
Authorization: {{token}}


### Logout
POST {{address}}/logout
Authorization: {{token}}

