### Signup
POST {{address}}/signup
Content-Type: application/json

{
  "name": "Test",
  "mail": "test1@mail.com",
  "authenticationString": "123",
  "age": 20,
  "country": "US"
}


### Login : Copy token and paste in your variables
POST {{address}}/login
Content-Type: application/json

{
  "mail": "test1@mail.com",
  "authenticationString": "123"
}


### Profile
GET {{address}}/profile
Content-Type: application/json
Authorization: {{token}}


### Logout
POST {{address}}/logout
Authorization: {{token}}


### Generate data
POST {{address}}/generate-data
Content-Type: application/json
Authorization: {{token}}


### Create a playlist
POST {{address}}/playlists/new
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Favorites"
}


### Create a playlist with songs
POST {{address}}/playlists/new
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Love",
  "songs": [
    {
      "name": "Canons"
    },
    {
      "name": "Powder"
    },
    {
      "name": "Test"
    }
  ]
}


### Get my playlists : Copy one playlist id and paste in your variables
GET {{address}}/playlists
Content-Type: application/json
Authorization: {{token}}


### Update a playlist
PUT {{address}}/playlists/{{playlistId}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Favorites - modified"
}


### Update a playlist and songs inside
PUT {{address}}/playlists/{{playlistId}}
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Love - modified",
  "songs": [
    {
      "name": "Powerful"
    },
    {
      "name": "Sunrise in rooftop"
    },
    {
      "name": "Test"
    }
  ]
}


### Delete a playlist
DELETE {{address}}/playlists/{{playlistId}}
Content-Type: application/json
Authorization: {{token}}